const psikolog = [
    {
        "id": 1,
        "name": "Dr. John Doe",
        "rating": 4.5,
        "status": "Online",
        "hari": "Senin",
        "image": "https://randomuser.me/api/portraits/women/1.jpg",
    },
    {
        "id": 2,
        "name": "Dr. Jane Doe",
        "rating": 4.5,
        "status": "Online",
        "hari": "Selasa",
        "image": "https://randomuser.me/api/portraits/men/2.jpg",
    },
    {
        "id": 3,
        "name": "Dr. John Doe",
        "rating": 4.5,
        "status": "Online",
        "hari": "Rabu",
        "image": "https://randomuser.me/api/portraits/men/3.jpg",
    },
    {
        "id": 4,
        "name": "Dr. Jane Doe",
        "rating": 4.5,
        "status": "Online",
        "hari": "Kamis",
        "image": "https://randomuser.me/api/portraits/men/4.jpg",
    },
    {
        "id": 5,
        "name": "Dr. John Doe",
        "rating": 4.5,
        "status": "Online",
        "hari": "Jumat",
        "image": "https://randomuser.me/api/portraits/men/5.jpg",
    },
    {
        "id": 6,
        "name": "Dr. John Doe",
        "rating": 4.5,
        "status": "Online",
        "hari": "Jumat",
        "image": "https://randomuser.me/api/portraits/men/6.jpg",
    },
    {
        "id": 7,
        "name": "Dr. John Doe",
        "rating": 4.5,
        "status": "Online",
        "hari": "Jumat",
        "image": "https://randomuser.me/api/portraits/men/7.jpg",
    },
    {
        "id": 8,
        "name": "Dr. John Doe",
        "rating": 4.5,
        "status": "Online",
        "hari": "Jumat",
        "image": "https://randomuser.me/api/portraits/men/2.jpg",
    },
    {
        "id": 9,
        "name": "Dr. John Doe",
        "rating": 4.5,
        "status": "Online",
        "hari": "Jumat",
        "image": "https://randomuser.me/api/portraits/men/2.jpg",
    },
]

export { psikolog };